### ISSUE TITLE
Publish in F-Droid

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [xaynetwork/xayn_discovery_app#601]
### Describe the problem you have :man_facepalming: :woman_shrugging:

This awesome app is unfortunately not listed in F-Droid.

----------

### Describe the solution you'd like :raising_hand_man: :raising_hand_woman:

I'd propose to add the corresponding metadata folder, ensure no non-free dependencies are included and open an F-Droid MR.

----------

### Describe alternatives you've considered :arrow_right_hook: :left_right_arrow: :arrow_up_down:

There are no good alternatives to F-Droid, maybe SiaSkynet?

**Comment by joecks** [comment]
Thanks for this first issue, could you please open up a PR request with the meta-data. Because we have no time right now to prioritize this our-self.
